//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shiftbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaintenanceTask()
        {
            this.WorkOrders = new HashSet<WorkOrder>();
            this.TagsTasks = new HashSet<TagsTask>();
            this.EquipmentCodeHistories = new HashSet<EquipmentCodeHistory>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EquipmentCodeId { get; set; }
        public string AssetDescription { get; set; }
        public string Pid { get; set; }
        public string SystemDescription { get; set; }
        public string MaintenanceType { get; set; }
        public string TaskDescription { get; set; }
        public string Comment { get; set; }
        public string Interval { get; set; }
        public string Unit { get; set; }
        public string PlantShutDownJob { get; set; }
        public string AtexZone { get; set; }
        public string AuxiliaryMaterial { get; set; }
        public string GreaseOilManufacturer { get; set; }
        public string GreaseOilType { get; set; }
        public string TopupAmount { get; set; }
        public Nullable<int> RoutineType { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual EquipmentCode EquipmentCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagsTask> TagsTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentCodeHistory> EquipmentCodeHistories { get; set; }
    }
}
