//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shiftbook.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EquipmentCode> EquipmentCodes { get; set; }
        public virtual DbSet<MaintenanceTask> MaintenanceTasks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<WorkOrderHistory> WorkOrderHistories { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TagsTask> TagsTasks { get; set; }
        public virtual DbSet<EquipmentCodeHistory> EquipmentCodeHistories { get; set; }
    }
}
