//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shiftbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsTask
    {
        public int Id { get; set; }
        public Nullable<int> TagsId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual MaintenanceTask MaintenanceTask { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
