//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shiftbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrder()
        {
            this.WorkOrder1 = new HashSet<WorkOrder>();
            this.WorkOrderHistories = new HashSet<WorkOrderHistory>();
            this.EquipmentCodeHistories = new HashSet<EquipmentCodeHistory>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FollowupParentId { get; set; }
        public Nullable<int> EquipmentCodeId { get; set; }
        public Nullable<int> MaintenanceTaskId { get; set; }
        public string Location { get; set; }
        public string Category { get; set; }
        public string OrderType { get; set; }
        public string OrderFor { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public string OrderDescription { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.TimeSpan> WorkTime { get; set; }
        public string File1Path { get; set; }
        public string File2Path { get; set; }
        public string File3Path { get; set; }
        public string File4Path { get; set; }
        public string File5Path { get; set; }
        public Nullable<int> IsClosed { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> TagsId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual EquipmentCode EquipmentCode { get; set; }
        public virtual MaintenanceTask MaintenanceTask { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrder> WorkOrder1 { get; set; }
        public virtual WorkOrder WorkOrder2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderHistory> WorkOrderHistories { get; set; }
        public virtual Type Type { get; set; }
        public virtual Tag Tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentCodeHistory> EquipmentCodeHistories { get; set; }
    }
}
